#!/bin/bash 

export PROJECT_NAME="Test project"
export GROUP_ID="io.github.vafeen"
export ARTIFACT_MODULE_NAME="test-publish-android"
export VERSION="1.0.1"

export SOURCES_PACKAGE="ru.vafeen.testpublish"
export PROJECT_DESCRIPTION="Test project"
export INCEPTION_YEAR=2025
export PROJECT_URL="https://github.com/vafeen/testproject"
export SCM_URL="https://github.com/vafeen/testproject.git"

export DEVELOPER_NAME="A"
export DEVELOPER_EMAIL="666av6@gmail.com"
export ORGANIZATION="A"
export ORGANIZATION_URL="https://example.com"
export ARTIFACT_NAME="${ARTIFACT_MODULE_NAME}" # if module name and atifact name are different
export SOURCE_CODE_PATH="$ARTIFACT_MODULE_NAME/src/main/java" # or kotlin

export ASSEMBLED_FILE="$ARTIFACT_MODULE_NAME/build/outputs/aar/$ARTIFACT_MODULE_NAME-release.aar"

source ./.sensitive # or use other env variables

./bash2sonatype/scripts/all_process false